migrate(
  (app) => {
    try {
      var oldCol = app.findCollectionByNameOrId('pedve012')
      app.delete(oldCol)
    } catch (_) {}

    var collection = new Collection({
      name: 'pedve012',
      type: 'base',
      listRule: "@request.auth.id != ''",
      viewRule: "@request.auth.id != ''",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id != ''",
      fields: [
        { name: 'pedido', type: 'text', required: true },
        { name: 'situacao', type: 'text' },
        { name: 'nota_fiscal', type: 'text' },
        { name: 'cod_cliente', type: 'text' },
        { name: 'cliente', type: 'text' },
        { name: 'uf', type: 'text' },
        { name: 'cidade', type: 'text' },
        { name: 'bairro', type: 'text' },
        { name: 'grupo', type: 'text' },
        { name: 'tipo_entrega', type: 'text' },
        { name: 'digitado', type: 'text' },
        { name: 'ate_envio', type: 'text' },
        { name: 'enviado', type: 'text' },
        { name: 'liberado', type: 'text' },
        { name: 'ate_lib', type: 'text' },
        { name: 'ate_sep', type: 'text' },
        { name: 'separado', type: 'text' },
        { name: 'conferido', type: 'text' },
        { name: 'ate_conf', type: 'text' },
        { name: 'ate_nf', type: 'text' },
        { name: 'nf_gerada', type: 'text' },
        { name: 'nfe_transmitida', type: 'text' },
        { name: 'ate_nfe', type: 'text' },
        { name: 'ate_transito', type: 'text' },
        { name: 'colocado_transito', type: 'text' },
        { name: 'ate_entrega', type: 'text' },
        { name: 'marcado_entrega', type: 'text' },
        { name: 'qtd_total', type: 'number', onlyInt: true },
        { name: 'nr_itens', type: 'number', onlyInt: true },
        { name: 'nr_ends', type: 'number', onlyInt: true },
        { name: 'cubagem_local_estoque', type: 'number' },
        { name: 'volume_local_estoque', type: 'number' },
        { name: 'emissao', type: 'date' },
        { name: 'prev_entr', type: 'date' },
        { name: 'digitacao', type: 'date' },
        { name: 'envio_liberacao', type: 'date' },
        { name: 'liberacao', type: 'date' },
        { name: 'inicio_sep', type: 'date' },
        { name: 'termino_sep', type: 'date' },
        { name: 'inicio_conf', type: 'date' },
        { name: 'termino_conf', type: 'date' },
        { name: 'gerar_nf', type: 'date' },
        { name: 'transmitir_nfe', type: 'date' },
        { name: 'transito', type: 'date' },
        { name: 'entrega', type: 'date' },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE INDEX idx_pedve012_pedido ON pedve012 (pedido)',
        'CREATE INDEX idx_pedve012_situacao ON pedve012 (situacao)',
        'CREATE INDEX idx_pedve012_tipo_entrega ON pedve012 (tipo_entrega)',
        'CREATE INDEX idx_pedve012_prev_entr ON pedve012 (prev_entr)',
        'CREATE INDEX idx_pedve012_envio_liberacao ON pedve012 (envio_liberacao)',
      ],
    })
    app.save(collection)
  },
  (app) => {},
)
